import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          {/* Go ahead -- */}
          Don't break your screen {' '}
            <Link href='#'>
              yet!
             {/* hold your breath!! */}
            </Link>
        </h1>

        <p className={styles.description}>
          Checkout new job template builder {' '}
          <Link href="/template">here!</Link>
          {/* <code className={styles.code}>here!</code> */}
        </p>

        <p className={styles.description}>
          Already applied? Track Your Application {' '}
          <Link href="/application">here!</Link>
          {/* <code className={styles.code}>here!</code> */}
        </p>
      </main>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a> 
      </footer> */}
    </div>
  )
}

export default Home
